- platform: yr

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

- platform: darksky
  api_key: !secret forecast_key
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - temperature_min
    - temperature_max
    - cloud_cover
    - humidity
    - hourly_summary
    - daily_summary

# - platform: template
#   sensors:
#     hue_hub:
#       friendly_name: 'Hue Hub'
#       value_template: >-
#           {%- if is_state("device_tracker.hue_hub", "home") %}
#               Online
#           {% else %}
#               Offline
#           {%- endif %}
#     appletv:
#       friendly_name: 'AppleTV'
#       value_template: >-
#           {%- if is_state("device_tracker.appletv", "home") %}
#               Online
#           {% else %}
#               Offline
#           {%- endif %}
#     printer:
#       friendly_name: 'Printer'
#       value_template: >-
#           {%- if is_state("device_tracker.printer", "home") %}
#               Online
#           {% else %}
#               Offline
#           {%- endif %}

- platform: systemmonitor
  resources:
    # - type: last_boot
    - type: since_last_boot
    - type: disk_use_percent
      arg: /

- platform: template
  sensors:
    - morning_announcement_last_triggered:
      value_template: "{% raw %}0{% endraw %}"
    - since_last_boot_templated:
      value_template: >-
        {%- set slb = states.sensor.since_last_boot.state.split(' ') -%}
        {%- set count = slb | length -%}
        {%- set hms = slb[count - 1] -%}
        {%- set hms_trimmed = hms.split('.')[0] -%}
        {%- set hms_split = hms_trimmed.split(':') -%}
        {%- set hours = hms_split[0] | int -%}
        {%- set minutes = hms_split[1] | int -%}
        {%- set seconds = hms_split[2] | int -%}
        {%- if count == 3 -%}
          {{ slb[0] ~ ' ' ~ slb[1] ~ ' ' }}
        {%- endif -%}
        {%- if hours > 0 -%}
          {%- if hours == 1 -%}
            1 hour
          {%- else -%}
            {{ hours }} hours
          {%- endif -%}
        {%- endif -%}
        {%- if minutes > 0 -%}
          {%- if hours > 0 -%}
            {{ ', ' }}
          {%- endif -%}
          {%- if minutes == 1 -%}
            1 minute
          {%- else -%}
            {{ minutes }} minutes
          {%- endif -%}
        {%- endif -%}
        {%- if seconds > 0 -%}
          {%- if hours > 0 or minutes > 0 -%}
            {{ ', ' }}
          {%- endif -%}
          {%- if seconds == 1 -%}
            1 second
          {%- else -%}
            {{ seconds }} seconds
          {%- endif -%}
        {%- endif -%}
    - sun_elevation:
        friendly_name: "Sun elevation"
        entity_id: sun.sun
        unit_of_measurement: 'degrees'
        value_template: "{{ states.sun.sun.attributes.elevation }}"

- platform: command_line
  name: "HA Last Reboot"
  command: cat /proc/uptime | awk '{printf "%0.f", $1}'
  scan_interval: 60
  value_template: >-
    {% set uptime = value | int %}
    {% set seconds = uptime % 60 %}
    {% set minutes = ((uptime % 3600) / 60) | int %}
    {% set hours = ((uptime % 86400) / 3600) | int %}
    {% set days = (uptime / 86400) | int %}
    {%- if days > 0 -%}
      {%- if days == 1 -%}
        1 day
      {%- else -%}
        {{ days }} days
      {%- endif -%}
      {{ ', ' }}
    {%- endif -%}
    {{ '%02d' % hours }}:{{ '%02d' % minutes }}
- platform: command_line
  name: "HA Uptime"
  command: echo "$(($(date +%s) - $(date -d "$(head -n1 /home/homeassistant/.homeassistant/home-assistant.log | cut -d' ' -f-2)" +%s)))"
  scan_interval: 60
  value_template: >-
    {% set uptime = value | int %}
    {% set seconds = uptime % 60 %}
    {% set minutes = ((uptime % 3600) / 60) | int %}
    {% set hours = ((uptime % 86400) / 3600) | int %}
    {% set days = (uptime / 86400) | int %}
    {%- if days > 0 -%}
      {%- if days == 1 -%}
        1 day
      {%- else -%}
        {{ days }} days
      {%- endif -%}
      {{ ', ' }}
    {%- endif -%}
    {{ '%02d' % hours }}:{{ '%02d' % minutes }}
